# Generated by Django 4.2.6 on 2023-10-22 18:51

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEPHIUserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'al_user_category',
                'db_table_comment': 'таблица категорий пользователей',
            },
        ),
        migrations.CreateModel(
            name='MEPHIUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(db_comment='Логин пользователя в системе, формируется по первым буквам ФИО', unique=True, verbose_name='логин')),
                ('email', models.EmailField(db_comment='Емейл адрес пользователя', max_length=254, unique=True, verbose_name='емейл адрес')),
                ('phone_number', models.CharField(db_comment='Номер телефона', unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{1}[-\\s]?\\(?\\d{3}\\)?[-\\s]?\\d{3}([-\\s]?\\d{2}){2}$')], verbose_name='номер телефона')),
                ('first_name', models.CharField(db_comment='Имя пользователя', max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(db_comment='Фамилия пользователя', max_length=50, verbose_name='фамилия')),
                ('patronymic', models.CharField(db_comment='Отчество пользователя', max_length=50, null=True, verbose_name='отчество')),
                ('date_registrate', models.DateTimeField(auto_now_add=True, db_comment='Дата регистрации пользователя', verbose_name='дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'al_user',
                'db_table_comment': 'таблица зарегистрированных пользователей',
                'get_latest_by': 'date_registrate',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
