# Generated by Django 4.2.5 on 2023-10-01 19:06

import annotate_application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mephiuser',
            name='user_category',
            field=models.ForeignKey(default=annotate_application.models.MEPHIUserCategory.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='mephi_user', to='annotate_application.mephiusercategory'),
        ),
    ]
