# Generated by Django 4.2.5 on 2023-10-24 06:32

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0002_alter_mephiuser_user_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ill_history', models.IntegerField(db_comment='Номер истории болезни', verbose_name='номер истории болезни')),
                ('first_name', models.CharField(db_comment='Имя пользователя', max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(db_comment='Фамилия пользователя', max_length=50, verbose_name='фамилия')),
                ('patronymic', models.CharField(db_comment='Отчество пользователя', max_length=50, null=True, verbose_name='отчество')),
                ('birthday', models.DateTimeField(db_comment='Дата рождения', verbose_name='дата рождения')),
                ('sex', models.BooleanField(db_comment='Пол 1 - мужской, 0 - женский', verbose_name='пол')),
                ('begin_date', models.DateTimeField(auto_now_add=True, db_comment='Дата начала актуальности записи', verbose_name='Дата начала актуальности записи')),
                ('end_date', models.DateTimeField(db_comment='Дата окончания актуальности записи', null=True, verbose_name='Дата окончания актуальности записи')),
                ('t_changed', models.IntegerField(db_comment='Состояние записи 0 - добавлена, 1 - изменена 2 - удалена', verbose_name='Состояние записи')),
                ('t_md5', models.CharField(db_comment='Хэш', max_length=32, verbose_name='Хэш')),
            ],
            options={
                'verbose_name': 'пациент',
                'verbose_name_plural': 'пациенты',
                'db_table': 'al_patient',
                'db_table_comment': 'таблица пациентов',
            },
        ),
        migrations.AlterModelManagers(
            name='mephiuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
