# Generated by Django 4.2.6 on 2023-10-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0002_mephiuser_user_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mephiuser',
            old_name='login',
            new_name='username',
        ),
    ]
