# Generated by Django 4.2.5 on 2023-11-18 10:48

import annotate_application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0002_mephiuser_user_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictCellsCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_name', models.CharField(db_comment='Наименование характеристики', verbose_name='Наименование характеристики')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
                'db_table': 'al_dict_cell_characteristic',
                'db_table_comment': 'словарь характеристик клеток',
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_name', models.CharField(db_comment='Название маркера', max_length=50, verbose_name='название маркера')),
                ('marker_type', models.CharField(choices=[('1', 'Тип 1'), ('2', 'Тип 2'), ('3', 'Тип 3')], db_comment='Тип маркера', max_length=2, verbose_name='Тип маркера')),
            ],
            options={
                'verbose_name': 'маркер',
                'verbose_name_plural': 'маркеры',
                'db_table': 'al_marker',
                'db_table_comment': 'справочник маркеров',
            },
        ),
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(db_comment='Цвет', max_length=6, verbose_name='Цвет')),
                ('x1', models.IntegerField(db_comment='X1', verbose_name='X1')),
                ('x2', models.IntegerField(db_comment='X2', verbose_name='X2')),
                ('y1', models.IntegerField(db_comment='Y1', verbose_name='Y1')),
                ('y2', models.IntegerField(db_comment='Y2', verbose_name='Y2')),
                ('description', models.TextField(blank=True, db_comment='Описание', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'маркировка',
                'verbose_name_plural': 'маркировки',
                'db_table': 'al_marking',
                'db_table_comment': 'таблица маркировок',
            },
        ),
        migrations.CreateModel(
            name='ResearchedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_object', models.IntegerField(db_comment='Количество объектов', verbose_name='Количество объектов')),
                ('sprout_type', models.CharField(choices=[('1', 'Тип 1'), ('2', 'Тип 2'), ('3', 'Тип 3')], db_comment='Тип ростка', verbose_name='Тип ростка')),
                ('norm', models.CharField(db_comment='Норма', verbose_name='Норма')),
            ],
            options={
                'verbose_name': 'объект исследования',
                'verbose_name_plural': 'объекты исследования',
                'db_table': 'al_researched_object',
                'db_table_comment': 'справочник объектов исследования',
            },
        ),
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.TextField(db_comment='Заключение', verbose_name='Заключение')),
            ],
            options={
                'verbose_name': 'результат исследования',
                'verbose_name_plural': 'результаты исследования',
                'db_table': 'al_research_result',
                'db_table_comment': 'справочник результатов исследования',
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(db_comment='Наименование термина', max_length=50, verbose_name='Наименование термина')),
                ('definition', models.TextField(db_comment='Определение', verbose_name='Определение')),
                ('description', models.TextField(blank=True, db_comment='Описание', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'термин',
                'verbose_name_plural': 'термины',
                'db_table': 'al_term',
                'db_table_comment': 'таблица терминов и определений',
            },
            bases=(models.Model, annotate_application.models.SCD2ModelMixin),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='t_changed',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='t_md5',
        ),
    ]
