# Generated by Django 4.2.5 on 2023-11-18 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0003_dictcellscharacteristics_marker_marking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateTimeField(db_comment='дата начала исследования', verbose_name='дата начала исследования')),
                ('date_end', models.DateTimeField(db_comment='дата окончания исследования', verbose_name='дата окончания исследования')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research', to='annotate_application.patient')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'исследование',
                'verbose_name_plural': 'исследования',
                'db_table': 'al_patient_research',
                'db_table_comment': 'справочник исследования пациента',
            },
        ),
    ]
