# Generated by Django 4.2.5 on 2023-11-18 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0004_patientresearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_type', models.CharField(choices=[('1', 'Тип 1'), ('2', 'Тип 2'), ('3', 'Тип 3')], db_comment='Тип препарата', verbose_name='Тип препарата')),
                ('patient_research', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication', to='annotate_application.patientresearch')),
            ],
            options={
                'verbose_name': 'препарат',
                'verbose_name_plural': 'препараты',
                'db_table': 'al_medication',
                'db_table_comment': 'справочник препаратов',
            },
        ),
    ]
