# Generated by Django 4.2.5 on 2023-11-18 12:47

import annotate_application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0006_immunophenotyping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=annotate_application.models.image_directory_path, verbose_name='Фото')),
                ('scale', models.IntegerField(db_comment='Масштаб', verbose_name='Масштаб')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cellimage', to='annotate_application.medication')),
            ],
            bases=(models.Model, annotate_application.models.SCD2ModelMixin),
        ),
    ]
