# Generated by Django 4.2.5 on 2023-11-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0007_cellimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellimage',
            options={'verbose_name': 'изображение клетки', 'verbose_name_plural': 'изображения клеток'},
        ),
        migrations.AlterModelTableComment(
            name='cellimage',
            table_comment='справочник изображений клеток',
        ),
        migrations.AlterModelTable(
            name='cellimage',
            table='al_cell_image',
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField(db_comment='Условия подготовки препарата', verbose_name='Условия подготовки препарата')),
                ('glass_type', models.CharField(db_comment='Тип стекла', verbose_name='Тип стекла')),
                ('artifacts', models.TextField(db_comment='Артефакты', verbose_name='Артефакты')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='systemsettings', to='annotate_application.medication')),
            ],
            options={
                'verbose_name': 'параметр системы',
                'verbose_name_plural': 'параметр системы',
                'db_table': 'al_settings',
                'db_table_comment': 'настройки системы',
            },
        ),
    ]
