# Generated by Django 4.2.5 on 2023-11-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0008_alter_cellimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellMarking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, db_comment='Комментарий', verbose_name='Комментарий')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cellmarking', to='annotate_application.cellimage')),
                ('marking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cellmarking', to='annotate_application.marking')),
            ],
            options={
                'db_table': 'al_cell_marking',
                'db_table_comment': 'маркировка изображения',
            },
        ),
    ]
