# Generated by Django 4.2.5 on 2023-11-18 14:31

import annotate_application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0009_cellmarking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=annotate_application.models.image_directory_path, verbose_name='Фото')),
                ('scale', models.IntegerField(db_comment='Масштаб', verbose_name='Масштаб')),
                ('cell_type', models.CharField(choices=[('1', 'Тип 1'), ('2', 'Тип 2'), ('3', 'Тип 3')], db_comment='Тип клетки', verbose_name='Тип клетки')),
            ],
            options={
                'verbose_name': 'клетка',
                'verbose_name_plural': 'клетки',
                'db_table': 'al_cell',
                'db_table_comment': 'справочник клеток',
            },
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='glass_type',
            field=models.CharField(choices=[('1', 'Тип 1'), ('2', 'Тип 2'), ('3', 'Тип 3')], db_comment='Тип стекла', verbose_name='Тип стекла'),
        ),
        migrations.AlterUniqueTogether(
            name='cellmarking',
            unique_together={('image', 'marking')},
        ),
        migrations.CreateModel(
            name='CellCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_comment='Значение', verbose_name='Значение')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cellcharacteristic', to='annotate_application.cell')),
                ('dictcharcteristics', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cellcharacteristic', to='annotate_application.dictcellscharacteristics')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='marking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cell', to='annotate_application.cellmarking'),
        ),
    ]
