# Generated by Django 4.2.5 on 2023-11-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0012_alter_patient_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Мужчина'), (0, 'Женщина')], db_comment='Пол 1 - мужской, 0 - женский', verbose_name='пол'),
        ),
    ]
