# Generated by Django 4.2.5 on 2023-11-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0013_alter_patient_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchresult',
            name='research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='researchresult', to='annotate_application.patientresearch'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='artifacts',
            field=models.IntegerField(db_comment='Артефакты', verbose_name='Артефакты'),
        ),
    ]
