# Generated by Django 4.2.5 on 2023-11-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0015_researchresult_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='mephiuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mephiuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
