# Generated by Django 4.2.5 on 2023-11-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0016_mephiuser_is_active_mephiuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_comment='Название типа', max_length=50, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'тип клетки',
                'verbose_name_plural': 'типы клетки',
                'db_table': 'al_cell_type',
                'db_table_comment': 'справочник типов клеток',
            },
        ),
        migrations.AlterModelOptions(
            name='cellmarking',
            options={'verbose_name': 'маркировка клетки', 'verbose_name_plural': 'маркировки клеток'},
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cell', to='annotate_application.celltype'),
        ),
    ]
