# Generated by Django 4.2.6 on 2023-11-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0020_systemlog_systemparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medication', to='annotate_application.patient'),
        ),
    ]
