# Generated by Django 4.2.5 on 2023-11-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_application', '0021_medication_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellimage',
            name='begin_date',
            field=models.DateTimeField(auto_now_add=True, db_comment='Дата начала актуальности записи', null=True, verbose_name='Дата начала актуальности записи'),
        ),
        migrations.AddField(
            model_name='cellimage',
            name='end_date',
            field=models.DateTimeField(db_comment='Дата окончания актуальности записи', null=True, verbose_name='Дата окончания актуальности записи'),
        ),
        migrations.AddField(
            model_name='cellimage',
            name='t_changed',
            field=models.IntegerField(db_comment='Состояние записи 0 - добавлена, 1 - изменена 2 - удалена', null=True, verbose_name='Состояние записи'),
        ),
        migrations.AddField(
            model_name='cellimage',
            name='t_md5',
            field=models.CharField(db_comment='Хэш', max_length=32, null=True, verbose_name='Хэш'),
        ),
    ]
